apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    uid: PCC52D03280B7034C
    url: host.docker.internal:5432
    database: mydb
    user: myuser
    secureJsonData:
      password: mypassword
    jsonData:
      sslmode: disable
      postgresVersion: 1600
